### ISSUE TITLE
Could you create a version of Base91 that exactly map to 13bits?

### ISSUE THREAD

**Issue by DonaldTsang** [ajg/base91#1]
I would like to have a B91 system where each 52b maps to exactly 4 char in base91. Is it possible?
2^13 in base91 is 90:2, that means everything from C" (90:2) to "" (90:90) should be invalid pairs.

I though Base91 will sometimes put 14bits into 2 characters due to "higher compression", and i wanted a version of base91 that WILL NOT switch between 13bit and 14bit blocks.

**Comment by ajg** [comment]
Hey @DonaldTsang, yes, in some cases (such as zero byte blocks) the efficiency improves to under 16/13. (Also, just to clarify, I did not create Base91—only this Haskell implementation; the original specification is here: http://base91.sourceforge.net/)

Anyway, I don't see why you couldn't create a variant of Base91 such as you describe, but I don't know if it'd be possible to make it backwards-compatible.
